### ISSUE TITLE
Recommendation: Add a Burn event in a similar way to the Mint.

### ISSUE THREAD

**Issue by junomonster** [Steemhunt/dixel-v2-contract#10]
# Description

There is a mint event on the `mint` function, but there isn't on the `burn` function.

https://github.com/Steemhunt/dixel-v2-contract/blob/657250a219bbf63e27b970336045d48640151b6f/contracts/DixelClubV2NFT.sol#L42

https://github.com/Steemhunt/dixel-v2-contract/blob/657250a219bbf63e27b970336045d48640151b6f/contracts/DixelClubV2NFT.sol#L115-L127

https://github.com/Steemhunt/dixel-v2-contract/blob/657250a219bbf63e27b970336045d48640151b6f/contracts/DixelClubV2NFT.sol#L108-L113

# Impact

The operator could not track the on-chain events easilty.

# Recommendation

Add a Burn event and emit it as same as the mint function for better handling on the off-chain side.

---

cc/ @jinmo

**Comment by sebayaki** [comment]
Fair enough.
I didn't implement Burn event because we don't really track burn event anymore on V2, but some creator might need that.
They can still track it using `Transfer` event, but to make it consistent with Mint event, I will add it.

Thanks for your suggestion!
