### ISSUE TITLE
The owner of the NFT contract must not be the contract address.

### ISSUE THREAD

**Issue by junomonster** [Steemhunt/dixel-v2-contract#12]
# Description

https://github.com/Steemhunt/dixel-v2-contract/blob/657250a219bbf63e27b970336045d48640151b6f/contracts/DixelClubV2Factory.sol#L74-L75

Factory calls `init` when the user creates the collection.

https://github.com/Steemhunt/dixel-v2-contract/blob/657250a219bbf63e27b970336045d48640151b6f/contracts/DixelClubV2NFT.sol#L51-L73

`init` function transfers its ownership to the owner which is the first argument of the function (msg.sender of the factory).

There is missing check of the owner should not be the contract.

# Impact

https://github.com/Steemhunt/dixel-v2-contract/blob/657250a219bbf63e27b970336045d48640151b6f/contracts/DixelClubV2NFT.sol#L100-L103

If the owner is a contract, the owner can control the possibility that user can mint or can not mint by reverting on the `recieve` function.

https://github.com/Steemhunt/dixel-v2-contract/blob/657250a219bbf63e27b970336045d48640151b6f/contracts/DixelClubV2NFT.sol#L313

The owner can initialize `maxSupply` only once which limits the maximum NFT counts. 

Nevertheless the `maxSupply` sets properly, reverting the owner contract allows the owner can control the miting possibility whenever the owner want.

# Recommendation

There is a `_transferOwnership` function which has an opportutnity to transfer the ownership to the contract address. So the design should be changed to the owner claims the mintingCost instead of sending the mintingCost to the owner diretly. Also, it could reduce the gas when the user mints the NFT.

cc/ @jinmo

**Comment by sebayaki** [comment]
Yeah it's probably less likely the owner wants to do that, but true - it's technically possible.
`transferOwnership` method is also public method, so the owner can transfer the ownership anytime they want.

claming minting cost would be better in terms of gas fee as well, but it would increase the risk of the contract being hacked.

I will discuss this issue more in the team and see if we're going to change the fee transfer design.

Thanks for your feedback :)

**Comment by sebayaki** [comment]
We've decided not to change this behavior because:

1. The owner of a collection can always prevent people from minting by updating `whitelistOnly` feature anyway
2. Claiming can save some gas fee on minting, but adds more security risk and extra interfaces

Thanks for your feedback though! 👍🏻
