### ISSUE TITLE
Improper minting starts date validation.

### ISSUE THREAD

**Issue by kirasys** [Steemhunt/dixel-v2-contract#13]
# Description
https://github.com/Steemhunt/dixel-v2-contract/blob/74f4095f1e159c870f7cdedba9e2b815386c5f33/contracts/DixelClubV2Factory.sol#L47-L63
There is no validation for `metaData.mintingBeginsFrom`. It allow an attacker to create NFT contract with an invalid minting starts date.

# Impacts
Attackers can create the NFT contract as if minting had started in the past. (e.g. Setting `metaData.mintingBeginsFrom` to zero means minting had started on the 1970-01-01) 

# Recommendation
In `createCollection()` function, If the `metaData.mintingBeginsFrom` less than `block.timestamp`, it should be replaced with  `block.timestamp`. 

**Example patch**
```diff
    function createCollection(
        string memory name,
        string memory symbol,
        Shared.MetaData memory metaData,
        uint24[PALETTE_SIZE] memory palette,
        uint8[TOTAL_PIXEL_COUNT] memory pixels
    ) external payable returns (address payable) {
        
+      // Neutralize minting starts date.
+      if (metaData.mintingBeginsFrom < block.timestamp)
+          metaData.mintingBeginsFrom = block.timestamp

        address payable nftAddress = _createClone(nftImplementation);
        DixelClubV2NFT newNFT = DixelClubV2NFT(nftAddress);
        newNFT.init(msg.sender, name, symbol, metaData, palette, pixels);
```

**Comment by sebayaki** [comment]
It was an intended behavior because there's no issue with setting `mintingBeginsFrom` to the past value (even just zero).

We only checks if the block timestamp is order than `mintingBeginsFrom` when it's set
```
if(uint40(block.timestamp) < _metaData.mintingBeginsFrom) revert DixelClubV2__NotStarted(_metaData.mintingBeginsFrom, uint40(block.timestamp));
```
so any value less than the current timestamp would be just considered as "start immediately"

**Comment by kirasys** [comment]
> It was an intended behavior because there's no issue with setting mintingBeginsFrom to the past value (even just zero).

I agree with this. There's no issue with the NFT contract itself.

However, any user can retrieve `mintingBeginsFrom`(timestamp that minting event begins) via `metaData()`.  I am not sure that this data will not be used off-chain.

https://github.com/Steemhunt/dixel-v2-contract/blob/6495dd6b59ce92cfce76a26d222bc1a3beccfb5a/contracts/DixelClubV2NFT.sol#L332-L344
https://github.com/Steemhunt/dixel-v2-contract/blob/6495dd6b59ce92cfce76a26d222bc1a3beccfb5a/contracts/Shared.sol#L11

**Comment by sebayaki** [comment]
Yeah I guess we can neutralize the data for just in case because it only adds a slight gas fee increase.
Thanks for your suggestion!
