### ISSUE TITLE
Receive function in DixelClubV2NFT might get users ether stuck in the contract

### ISSUE THREAD

**Issue by assafom** [Steemhunt/dixel-v2-contract#14]
DixelClubV2NFT  [has](https://github.com/Steemhunt/dixel-v2-contract/blob/main/contracts/DixelClubV2NFT.sol#L54) an ether receive function:
```
    receive() external payable {}
```
It is not necessary for the functioning of the contract - as ether should only be sent during a `mint` call.
The `receive` function will enable sending ether to the contract outside of the `mint` function.
This ether will be stuck in the contract, as there's no way to pull ether.
While this is unlikely to happen, this means that if somebody accidently sends ether (/native token) to the contract without calling `mint`, his funds would be lost.

Since the contract does not need this method, and it might cause harm, I suggest removing this `receive` function.

**Comment by sebayaki** [comment]
This issue was fixed with https://github.com/Steemhunt/dixel-v2-contract/pull/4/commits/b884265e37c493808a4af7061abb6ba6db31d120

Thanks for pointing this out.
