### ISSUE TITLE
SVGGenerator generates extra horizontal pixel - image dimensions becomes 24*25

### ISSUE THREAD

**Issue by assafom** [Steemhunt/dixel-v2-contract#15]
The SVGGenerator generates images which are 25 pixels wide. You can see it for example in test-svg.svg - we have the following SVG path:
```
M0 1h25
```
This tells the SVG to draw 25 pixels - but the size of the canvas is only 24 pixels.
I believe the culprit is [this line](https://github.com/Steemhunt/dixel-v2-contract/blob/main/contracts/SVGGenerator.sol#L42), which is executed on the last pixel of the line:
```
                    paths[current] = string(abi.encodePacked(paths[current], "h", ColorUtils.uint2str(width + 1)));
```
If we change it to draw only `width` instead of `width + 1`, the resulting canvas would be 24 pixels wide, as it should.

At the moment it is drawing the last pixel of each row twice.

To see why - let's say the last pixel has changed in color. In the current implementation, this is the code:
```
                if (prev == current) {
                    width++;
                } else {
                    paths[prev] = string(abi.encodePacked(paths[prev], "h", ColorUtils.uint2str(width)));
                    width = 1;

                    paths[current] = string(abi.encodePacked(paths[current], "M", ColorUtils.uint2str(x), " ", ColorUtils.uint2str(y)));
                }

                if (x == CANVAS_SIZE - 1) {
                    paths[current] = string(abi.encodePacked(paths[current], "h", ColorUtils.uint2str(width + 1)));
                }
```
So the "else" block would set the width to 1, and then the `if (x == CANVAS_SIZE - 1)` block would increment the width to 2 - but the real width should be only 1.
This is why the width should be only `width` and not `width + 1`.

It is now my bed time, tomorrow if I'll have time I'll try adding some tests for this 🙂

**Comment by sebayaki** [comment]
I guess we had a reason we put `width + 1` there (probably the same reason we se thet viewBox="0 -0.5 24 24"), but I don't really remember.. lol

I tested with some other inputs, and it seems you're right. There's no need to put an extra width outside of the viewport.
I just fixed the SVG generator code and added one more test case.

Thanks heaps 👍🏻

**Comment by assafom** [comment]
👍 Great mate, you're welcome 🙂 also for the pixels gas thing 👍 🥂
