### ISSUE TITLE
_initializedAt bool instead of uint40

### ISSUE THREAD

**Issue by inmarelibero** [Steemhunt/dixel-v2-contract#25]
Hi, can't `_initializedAt` at https://github.com/Steemhunt/dixel-v2-contract/blob/d11a586f289b479e8d0afc72e89deb3991a92aee/contracts/DixelClubV2NFT.sol#L46 be a `bool` instead?

I saw it's used very little, and I don't get clearly its function. Can you clarify it?

**Comment by Nipol** [comment]
related, https://github.com/Steemhunt/dixel-v2-contract/pull/4#discussion_r888680612

**Comment by sebayaki** [comment]
It's being used to sort collections by historical order on the main list of the web front-end
