### ISSUE TITLE
Community Audit - Reward Distribution! 💸

### ISSUE THREAD

**Issue by sebayaki** [Steemhunt/dixel-v2-contract#28]
Community Audit for Dixel V2 contract is now over.
In total, 13 developers have contributed in this review process.

@contract-whale
@Nipol 
@assafom 
@syl-doo2
@dbadoy 
@keon
@sirius651 
@jonghwaC
@n1net4il
@kjsman
@junomonster
@kirasys
@inmarelibero

Thank you guys all for your valuable time and contributions 👍🏻

I'm going to evaluate all contributions as fair as possible considering the importance of the contributions and amount of work put into the reviewing process.

While I'm working on the distribution details, please leave your wallet address here for receiving your reward (USDT wallet, Please specify the network: Ethereum, BNB Smart Chain, Solana, AVAX C-Chain, Polygon, Tron network).
If you don't want to put your address here publicly, you can send it to our email instead: admin@hunt.town

**Comment by dbadoy** [comment]
Here is my USDT wallet,
0xa7e25d247990a2b1626cb9df6ab27be1421b0b24
network : BNB Smart Chain

I'm looking forward to that open the main service Dixel Club v2.

thanks.

2022년 6월 13일 (월) 오전 11:43, sydneyitguy ***@***.***>님이 작성:

**Comment by kjsman** [comment]
Thank you for the great program -- My addrsss is `0xBCA55Dd19A86Cf50cfeb7ad38ee6c1007B3b9618` (Ethereum).

**Comment by contract-whale** [comment]
Looking forward to this amazing journey!!    

`0x80ba325fd1299ef935d3f905178e372e52173511`  (Polygon)

**Comment by n1net4il** [comment]
I hope this project to be successful :)

`0xfC0dA319f2795e0Ac0Ac4740156264c32d84CAFa` (Ethereum)

**Comment by Nipol** [comment]
Great!
yoonsung.eth `0x4Fe992E566F8a28248acC4cB401b7FfD7dF959B0` Ethereum

**Comment by jonghwaC** [comment]
Thanks!
`0xe2b6b66839C9E0fa81616A69edb6591926Ef3F47` (BNB Smart Chain)

**Comment by kirasys** [comment]
Thanks for the great project!
Me(kirasys) and my teammate([junomonster](https://github.com/junomonster)) hope to receive the reward at same address.
`0xd3a0776Afba9633d6088C6ae172bCA78E7fC9434` (BNB Smart Chain)

**Comment by junomonster** [comment]
> Thanks for the great project! Me(kirasys) and my teammate([junomonster](https://github.com/junomonster)) hope to receive the reward at same address. `0xd3a0776Afba9633d6088C6ae172bCA78E7fC9434` (Ethereum)

Yeah

**Comment by sirius651** [comment]
Great!
`0x3BDB8baC386815E07E0A089Dd8756FF32f678c63` Ethereum

**Comment by sebayaki** [comment]
<img width="810" alt="image" src="https://user-images.githubusercontent.com/1332279/173318254-990d8807-976f-415a-b8b5-8732b64d69bc.png">

Here's the distribution table the team has summarized and evaluated.
Hope everyone is happy with the distribution 🙏🏻 (If you have any concerns or opinion on the distribution, please comment down here so we can discuss together).

@syl-doo2
@keon
@inmarelibero
I haven't received the wallet address from you guys. Please let me know when you see this message.

We're going to launch Dixel Club V2 privately with few verified collection creators soon, including a collection for the audit contributors. You guys will be automatically added on the whitelist for minting 😉

Thanks again for your participation and let's keep in touch! ❤️

**Comment by inmarelibero** [comment]
@sydneyitguy you have been to kind, didn't think to get anything. I sent an email, thanks!

**Comment by kirasys** [comment]
@sydneyitguy we have changed the network to BSC :)

FYI : https://github.com/Steemhunt/dixel-v2-contract/issues/28#issuecomment-1153505271

**Comment by sebayaki** [comment]
I've just sent all rewards 💸  (except @syl-doo2 and @keon - please send me the wallet address anytime you're available.)

Thank you guys all for your time and contribution! Hope to see you guys again soon!

**Comment by syl-doo2** [comment]
Thanks! 

My ETH address is 0x5E011a8407e51131a2BeF1E4a4B18BdC7EEa2D87

**Comment by sebayaki** [comment]
@contract-whale
@Nipol
@assafom
@syl-doo2
@dbadoy
@keon
@sirius651
@jonghwaC
@n1net4il
@kjsman
@junomonster
@kirasys
@inmarelibero

Hey guys! We're launching Mint Club V2 again and holding another audit event! 
This time, the total bounty is up to $30,000 USDT! 🙌🏻

Check out more details at: 
https://github.com/Steemhunt/mint.club-v2-contract/blob/main/COMMUNITY_AUDIT.md

**Comment by Richweller10** [comment]
My Eth addy
0x54bf5ccA8c9F900881990f8dd8305434C9589a9c
