### ISSUE TITLE
Withdraw?

### ISSUE THREAD

**Issue by EatTheNFT** [Steemhunt/dixel-v2-contract#29]
Hello,

How do you withdraw NFT sales from this contract?

**Comment by sebayaki** [comment]
https://github.com/Steemhunt/dixel-v2-contract/blob/main/contracts/DixelClubV2NFT.sol#L116

As you can see here, the minting cost is transferred to the creator directly on every minting.

**Comment by EatTheNFT** [comment]
0x1f3Af095CDa17d63cad238358837321e95FC5915
Etherscan

But here is a balance in the contract

There is an entire "gas eater" at Address.sol, but no security params?

**Comment by sebayaki** [comment]
That's an old mainnet testing contract we deployed yesterday, and those transactions and the balance are from wrong deposits made previously on that address because the contract address happened to be the same as [Mint Token contract](https://www.bscscan.com/address/0x1f3Af095CDa17d63cad238358837321e95FC5915) on BSC (using the same deploy wallet and nounce).

>There is an entire "gas eater" at Address.sol, but no security params?

What do you mean by this?

**Comment by EatTheNFT** [comment]
I was looking at your repo and check if it is suitable for production usage.

> There is an entire "gas eater" at Address.sol, but no security params?

I mean if other deployed contracts happens to receive funds by some way, the creator is unable to withdraw them by any way?
It is not quite unsafe for owner? 

Let's say someone deploy this contract and wants to offer 100 NFT's for free, using a script to update price when total supply reach 100 (it is quite simple to create a monitor script like that).
But in the contract, will be dropped some funds accidentally, they will be stuck forever, right?
In this case, even if he try to go reentrant on minting function, he will not fulfill the msg.value condition to recover tokens. Impossible self reentrancy attack.

It wouldn't be safer if owner has a withdrawal button that calls "sendValue" function to clean address balance?
I also have a github repo with NFT Smart Contract, which distribute ether when users mint tokens, but i included a withdrawal function, in case there are some tokens stucked.

I'm just curious about your approach, this is the reason i opened this issue.

**Comment by sebayaki** [comment]
https://github.com/Steemhunt/dixel-v2-contract/commit/cad595ba5f7459b9e6336da9ddb25fca1eb61538

Users can no longer send value to the contract directly with this fix
