### ISSUE TITLE
No need to traverse whitelist array twice when minting

### ISSUE THREAD

**Issue by assafom** [Steemhunt/dixel-v2-contract#6]
Note: although there is another discussion on whether to change the implementation to mapping, I'm posting this issue in case you decide to stay with the array.

At the moment, when minting, this is the whitelist process:
```
        // For whitelist only collections
        if (_metaData.whitelistOnly) {
            require(isWhitelistWallet(msg.sender), "NOT_IN_WTHIELIST");

            _removeWhitelist(msg.sender); // decrease allowance by 1
        }
```
This means the contract will iterate once over the whitelist array in `isWhitelistWallet`, and then iterate again on `_removeWhitelist`.
While the second iteration will be cheaper, it will still be 100 gas for every address that is read from the whitelist. So address #200 will have to pay unnecessary 20000 gas.

**Instead of doing this, you can skip calling `isWhitelistWallet`, and just call `_removeWhitelist`, and change it so it will revert if the address it not found.**

So you can change the `_removeWhitelist` from this:
```
    function _removeWhitelist(address wallet) private {
        for (uint256 i = 0; i < _whitelist.length; i++) {
            if (_whitelist[i] == wallet) {
                _whitelist[i] = _whitelist[_whitelist.length - 1]; // put the last element into the delete index
                _whitelist.pop(); // delete the last element to decrease array length;

                break; // delete the first matching one and stop
            }
        }
    }
```

To this:
```
    function _removeWhitelist(address wallet) private {
        for (uint256 i = 0; i < _whitelist.length; i++) {
            if (_whitelist[i] == wallet) {
                _whitelist[i] = _whitelist[_whitelist.length - 1]; // put the last element into the delete index
                _whitelist.pop(); // delete the last element to decrease array length;

                return; // delete the first matching one and stop
            }
        }
        require(false, "NOT_IN_WHITELIST")
    }
```

And change the minting whitelist block to this:
```
        // For whitelist only collections
        if (_metaData.whitelistOnly) {
            _removeWhitelist(msg.sender); // decrease allowance by 1, revert if not in whitelist
        }
```

And this will save you O(n) of iteration on the list.

Note: `removeWhitelist` also uses `_removeWhitelist`, so make sure you're ok with it reverting if the owner supplies an address which is not whitelisted. If not, just change `removeWhitelist` implementation to not revert if not found... You probably get the picture.

**Comment by sebayaki** [comment]
Thanks for pointing this out. I always forget "reading" also cost a lot of gas in Solidity.. lol

Related to #2 - will be fixed with the issue
