### ISSUE TITLE
Pass position in whitelist when minting to save lots of gas

### ISSUE THREAD

**Issue by assafom** [Steemhunt/dixel-v2-contract#8]
I just had a cool idea to keep the whitelist as array, but save lots of gas 🙂
You can keep the current mint method if you want, but also add another one, **which will take an additional parameter - the sender's position in the whitelist array**.
It will then just verify that `_whitelist[parameter] == msg.sender`, and then delete that value.

This way it does not have to traverse the array at all! So obviously it's a huge difference.

How it will work is that the front end can search for an address's position in the whitelist array (free view function), and then pass that as parameter to the new mint function.

I think this is probably clear enough, let me know of any questions.

**Comment by assafom** [comment]
(note: I am not creating a PR as Nipol has an open PR with lots of changes, I don't wanna create conflicts as anyway this and my previous issue are simple changes)

**Comment by sebayaki** [comment]
Oh.. wow. You're genius!
I just commented on [ #2 ](https://github.com/Steemhunt/dixel-v2-contract/issues/2#issuecomment-1145086020), but couldn't think of this genius hacky way :)

I guess this could be the best way solving whitelist gas issue!
